version: '3.9'

services:
  # Swagger Editor Next
  editor:
    image: swaggerapi/swagger-editor:next-v5
    container_name: swagger-editor
    ports:
      - 8001:80
    volumes:
      - ./openapi.yml:/openapi/openapi.yml

  # Swagger UI
  ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8002:8080
    environment: # 環境設定
      SWAGGER_JSON: /openapi/openapi.yml
    volumes:
      - ./openapi.yml:/openapi/openapi.yml

# APIアプリケーションと連携する場合以下をアンコメントしてください
# networks:
#   phpunit_web:
#     external: true