openapi: 3.0.3

info:
  title: 美容院予約API
  description: |
    ## 説明
    * 美容院の予約、確認を行うAPI
    ## 機能
    - 予約 一覧取得
    - 予約 登録
    - 予約 取得
    - 予約 更新
    - 予約 削除
  version: 1.0.0

servers:
  - url: 'http://localhost:{port}/{basePath}/api'
    description: 開発環境サーバー
    variables:
      port:
        enum:
          - '8080'
          - '80'
        default: '8080'
      basePath:
        enum:
          - 'v1'
          - 'v2'
        default: 'v1'

paths:
  /reservations:
    get:
      summary: 予約 一覧取得
      description: 予約一覧を取得する
      tags:
        - reservation
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReservationInfo'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
    post:
      summary: 予約 登録
      description: 予約を登録する
      tags:
        - reservation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationInfo'
      responses:
        '200':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationInfo'
        '422':
          $ref: '#/components/responses/422-UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500-InternalServerError'

  /reservations/{id}:
    get:
      summary: 予約 詳細取得
      description: 予約を取得する
      tags:
        - reservation
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReservationInfo'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalServerError'

    put:
      summary: 予約 更新
      description: 予約を更新する
      tags:
        - reservation
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationInfo'
      responses: 
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/ReservationInfo'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '422':
          $ref: '#/components/responses/422-UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500-InternalServerError'

    delete:
      summary: 予約 削除
      description: 予約をキャンセルする
      tags:
        - reservation
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: 削除成功
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalServerError'

components:
  schemas:
    ReservationInfo:
      type: object
      properties:
        hair_salon:
          description: 店舗名
          type: string
        hairdresser:
          description: 美容師
          type: string
        id:
          description: 予約ID
          type: string
        reservation_date_time:
          description: 予約日時
          type: string
          format: date-time
          example: 'YYYY/MM/DD'

  responses:
    400-BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Bad Request
            required:
              - message
    403-Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Forbidden
            required:
              - message
    404-NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not Found
            required:
              - message
    422-UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unprocessable Entity
              errors:
                type: object
                properties:
                  string:
                    type: array
                    items:
                      type: string
                      example: hairdresser required
    500-InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal Server Error
            required:
              - message

