openapi: 3.0.3

info:
  title: サロンAPI
  description: サロンのCRUDを行うAPI
  version: 1.0.0

servers:
  - url: 'http://localhost:{port}/{basePath}/api'
    description: 開発環境サーバー
    variables:
      port:
        enum:
          - '8080'
          - '80'
        default: '8080'
      basePath:
        enum:
          - 'v1'
          - 'v2'
        default: 'v1'

paths:
  /salons:
    get:
      summary: サロン 一覧取得
      description: サロン一覧を取得する
      tags:
        - salon
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Index'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
    post:
      summary: サロン 登録
      description: サロンを登録する
      tags:
        - salon
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Detail'
      responses:
        '200':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detail'
        '422':
          $ref: '#/components/responses/422-UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
  /salons/{id}:
    get:
      summary: サロン 詳細取得
      description: サロンを取得する
      tags:
        - salon
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Detail'
        '400':
          $ref: '#/components/responses/400-BadRequest'
        '403':
          $ref: '#/components/responses/403-Forbidden'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
    put:
      summary: サロン 更新
      description: サロンを更新する
      tags:
        - salon
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      requestBody: 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Detail'
      responses: 
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/Detail'
        '404':
          $ref: '#/components/responses/404-NotFound'
        '422':
          $ref: '#/components/responses/422-UnprocessableEntity'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
    delete:
      summary: サロン 削除
      description: サロンを削除する
      tags:
        - salon
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '204':
          description: 削除成功
        '404':
          $ref: '#/components/responses/404-NotFound'
        '500':
          $ref: '#/components/responses/500-InternalServerError'
components:
  schemas:
    Index:
      description: サロン一覧情報
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    Detail:
      description: サロン個別情報
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        zipcode:
          type: string
        address:
          type: string
        phone_number:
          type: string
        start_time:
          type: string
        closing_time:
          type: string
        holiday:
          type: string
        payment_methods:
          type: string
  responses:
    400-BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Bad Request
            required:
              - message
    403-Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Forbidden
            required:
              - message
    404-NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not Found
            required:
              - message
    422-UnprocessableEntity:
      description: Unprocessable Entity
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Unprocessable Entity
              errors:
                type: object
                properties:
                  string:
                    type: array
                    items:
                      type: string
                      example: hairdresser required
    500-InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal Server Error
            required:
              - message

